import { getFrameworkById } from "../frameworks/index.js";
import type { ResolverOutput } from "../types.js";

export interface ClaudeMdOptions {
	projectName: string;
	primaryFramework?: string;
	companionFrameworks?: string[];
	aiProviders?: string[];
	proxy?: string;
	domain?: string;
	deployTarget?: string;
	notificationProviders?: string[];
}

/**
 * Generates a workspace-specific CLAUDE.md that provides Claude Code sessions
 * running inside the container with instant context about the stack.
 */
export function generateClaudeMd(resolved: ResolverOutput, options: ClaudeMdOptions): string {
	const {
		projectName,
		primaryFramework = "openclaw",
		companionFrameworks = [],
		aiProviders = [],
		proxy = "none",
		domain,
		deployTarget = "local",
		notificationProviders = [],
	} = options;

	const framework = getFrameworkById(primaryFramework);
	const frameworkName = framework?.name ?? "OpenClaw";
	const sections: string[] = [];

	// ── Header ──────────────────────────────────────────────────────────────

	sections.push(`# ${projectName} — Stack Context

> Auto-generated by better-openclaw. This file gives Claude Code sessions instant context about your stack.
`);

	// ── Architecture ────────────────────────────────────────────────────────

	const archLines = [`- **Primary framework:** ${frameworkName}`];
	if (companionFrameworks.length > 0) {
		const names = companionFrameworks.map((id) => getFrameworkById(id)?.name ?? id).join(", ");
		archLines.push(`- **Companion frameworks:** ${names}`);
	}
	if (proxy !== "none") {
		archLines.push(`- **Proxy:** ${proxy}${domain ? ` (${domain})` : ""}`);
	}
	archLines.push(`- **Deploy target:** ${deployTarget}`);

	sections.push(`## Architecture

${archLines.join("\n")}
`);

	// ── Services ────────────────────────────────────────────────────────────

	const serviceRows = resolved.services
		.map(({ definition: def }) => {
			const ports = def.ports
				.filter((p) => p.exposed)
				.map((p) => String(p.container))
				.join(", ");
			return `| ${def.icon} ${def.name} | ${ports || "—"} | ${def.description.split(".")[0]} |`;
		})
		.join("\n");

	sections.push(`## Services

| Service | Ports | Description |
|---------|-------|-------------|
${serviceRows}
`);

	// ── AI Providers ────────────────────────────────────────────────────────

	if (aiProviders.length > 0) {
		const providerLines = aiProviders
			.map((p) => {
				const envKey =
					p === "ollama-cloud"
						? "OLLAMA_API_KEY"
						: ["ollama", "lmstudio", "vllm"].includes(p)
							? null
							: `${p.toUpperCase()}_API_KEY`;
				return envKey ? `- ${p} (\`${envKey}\`)` : `- ${p} (local)`;
			})
			.join("\n");

		sections.push(`## AI Providers

${providerLines}
`);
	}

	// ── Key Paths ───────────────────────────────────────────────────────────

	sections.push(`## Key Paths

- **Config:** \`openclaw/config/openclaw.json\`
- **Workspace:** \`openclaw/workspace/\`
- **Skills:** \`openclaw/workspace/skills/\`
- **Compose:** \`docker-compose.yml\`
- **Environment:** \`.env\`
`);

	// ── Environment Variables ────────────────────────────────────────────────

	const envVarLines = [
		"- `OPENCLAW_GATEWAY_TOKEN` — Gateway auth token",
		"- `OPENCLAW_GATEWAY_PORT` — Gateway port (default: 18789)",
		"- `OPENCLAW_BRIDGE_PORT` — WebSocket bridge port (default: 18790)",
		"- `PUID` / `PGID` — Container user/group ID for file ownership",
	];

	sections.push(`## Environment Variables

All secrets are in \`.env\`. Key variables:

${envVarLines.join("\n")}
`);

	// ── Notifications ───────────────────────────────────────────────────────

	if (notificationProviders.length > 0) {
		sections.push(`## Notifications

Configured providers: ${notificationProviders.join(", ")}

Notifications are sent on task completion and errors. Configure webhook URLs in \`.env\`.
`);
	}

	// ── Common Commands ─────────────────────────────────────────────────────

	sections.push(`## Common Commands

\`\`\`bash
./scripts/start.sh       # Start all services (auto-onboards on first boot)
./scripts/stop.sh        # Stop all services
./scripts/status.sh      # Show service status
./scripts/update.sh      # Pull latest images and restart
./scripts/backup.sh      # Backup all volumes
docker compose logs -f   # Follow all logs
docker compose ps        # List running services
\`\`\`
`);

	// ── Guidelines ──────────────────────────────────────────────────────────

	sections.push(`## Guidelines

- All service configuration is in \`docker-compose.yml\` and profile files
- Secrets are in \`.env\` — never commit this file
- Skills are in \`openclaw/workspace/skills/\` — each has a \`SKILL.md\` with usage
- The gateway runs on port 18789, bridge on 18790
- Use \`docker compose exec openclaw-gateway <command>\` to run commands inside the gateway
`);

	return sections.join("\n");
}
