import type { ResolverOutput } from "../types.js";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface HealthCheckOptions {
	projectName: string;
	deploymentType?: "docker" | "bare-metal" | "local";
}

// ─── Generator ──────────────────────────────────────────────────────────────

/**
 * Generates stack-specific health check and verification scripts.
 *
 * Each generated script is dynamic — it contains the exact service names,
 * ports, and health check commands from the resolved stack so users get
 * a precise, zero-configuration verifier.
 */
export function generateHealthCheck(
	resolved: ResolverOutput,
	options: HealthCheckOptions,
): Record<string, string> {
	const files: Record<string, string> = {};

	files["scripts/health-check.sh"] = generateBashScript(resolved, options);
	files["scripts/health-check.ps1"] = generatePowerShellScript(resolved, options);

	return files;
}

// ─── Service metadata extraction ────────────────────────────────────────────

interface ServiceCheck {
	id: string;
	name: string;
	icon: string;
	ports: Array<{ host: number; container: number; description: string; exposed: boolean }>;
	healthCheckCmd: string | null;
}

function extractServiceChecks(resolved: ResolverOutput): ServiceCheck[] {
	return resolved.services.map((svc) => ({
		id: svc.definition.id,
		name: svc.definition.name,
		icon: svc.definition.icon,
		ports: svc.definition.ports.map((p) => ({
			host: p.host,
			container: p.container,
			description: p.description,
			exposed: p.exposed,
		})),
		healthCheckCmd: svc.definition.healthcheck?.test ?? null,
	}));
}

function escapeShell(s: string): string {
	return s.replace(/'/g, "'\\''").replace(/"/g, '\\"');
}

// Use L() to build lines safely — avoids template literal issues with shell syntax
function L(...parts: string[]): string {
	return parts.join("");
}

// ─── Bash Script ────────────────────────────────────────────────────────────

function generateBashScript(resolved: ResolverOutput, options: HealthCheckOptions): string {
	const checks = extractServiceChecks(resolved);
	const name = options.projectName;
	const total = checks.length;

	// Build per-service docker check calls
	const dockerChecks: string[] = [];
	for (const svc of checks) {
		dockerChecks.push(L("  # ── ", svc.icon, " ", svc.name, " ──"));
		dockerChecks.push(L('  check_container "', svc.id, '" "', svc.name, '" "', svc.icon, '"'));
		for (const p of svc.ports.filter((pp) => pp.exposed)) {
			dockerChecks.push(
				L('  check_port "', svc.id, '" ', String(p.host), ' "', p.description, '"'),
			);
		}
		if (svc.healthCheckCmd) {
			dockerChecks.push(
				L('  check_health_cmd "', svc.id, '" "', escapeShell(svc.healthCheckCmd), '"'),
			);
		} else {
			dockerChecks.push("  # No healthcheck defined — skipping exec check");
		}
		dockerChecks.push("");
	}

	// Build per-service bare-metal check calls
	const bmChecks: string[] = [];
	for (const svc of checks) {
		bmChecks.push(L("  # ── ", svc.icon, " ", svc.name, " (bare-metal) ──"));
		bmChecks.push(L('  check_process "', svc.id, '" "', svc.name, '" "', svc.icon, '"'));
		for (const p of svc.ports.filter((pp) => pp.exposed)) {
			bmChecks.push(L('  check_port "', svc.id, '" ', String(p.host), ' "', p.description, '"'));
		}
		bmChecks.push("");
	}

	// Build the log-scan service list
	const svcIdList = checks.map((s) => `"${s.id}"`).join(" ");

	const lines: string[] = [
		"#!/usr/bin/env bash",
		"set -uo pipefail",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		L("# 🐾 OpenClaw Stack Health Check — ", name),
		"# ═══════════════════════════════════════════════════════════════════════",
		"#",
		"# Auto-generated verification script for your stack.",
		L("# Checks ", String(total), " services across 6 phases:"),
		"#   1. Environment     — prerequisites, .env, secrets",
		"#   2. Container       — running state, health status, restart count",
		"#   3. Port            — TCP reachability for exposed ports",
		"#   4. Health Command  — execute each service's health check",
		"#   5. Resources       — memory/CPU warnings",
		"#   6. Logs            — scan for ERROR/FATAL/panic patterns",
		"#",
		"# Usage:",
		"#   ./scripts/health-check.sh           # Full check",
		"#   ./scripts/health-check.sh --quick   # Skip log scan",
		"#   ./scripts/health-check.sh --json    # Output as JSON",
		"#",
		"# Exit codes: 0 = all healthy, 1 = some issues, 2 = critical failure",
		"# ═══════════════════════════════════════════════════════════════════════",
		"",
		'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
		'PROJECT_DIR="$(dirname "$SCRIPT_DIR")"',
		'cd "$PROJECT_DIR"',
		"",
		"# ── Arguments ────────────────────────────────────────────────────────",
		"QUICK_MODE=false",
		"JSON_MODE=false",
		"VERBOSE=false",
		'for arg in "$@"; do',
		'  case "$arg" in',
		"    --quick)  QUICK_MODE=true ;;",
		"    --json)   JSON_MODE=true ;;",
		"    --verbose|-v) VERBOSE=true ;;",
		"  esac",
		"done",
		"",
		"# ── Colour helpers ───────────────────────────────────────────────────",
		'if [ -t 1 ] && [ "$JSON_MODE" = false ]; then',
		"  RED='\\033[0;31m'; GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'",
		"  CYAN='\\033[0;36m'; DIM='\\033[2m'; BOLD='\\033[1m'; NC='\\033[0m'",
		"else",
		"  RED=''; GREEN=''; YELLOW=''; CYAN=''; DIM=''; BOLD=''; NC=''",
		"fi",
		"",
		"# ── Counters ─────────────────────────────────────────────────────────",
		L("TOTAL=", String(total)),
		"HEALTHY=0",
		"WARNING=0",
		"FAILED=0",
		"ERRORS=()",
		"WARNINGS_LIST=()",
		"SERVICE_RESULTS=()",
		"",
		"# ── Utility functions ────────────────────────────────────────────────",
		'pass()     { echo -e "  ${GREEN}✅ $*${NC}"; HEALTHY=$((HEALTHY + 1)); }',
		'warn_svc() { echo -e "  ${YELLOW}⚠️  $*${NC}"; WARNING=$((WARNING + 1)); WARNINGS_LIST+=("$*"); }',
		'fail()     { echo -e "  ${RED}❌ $*${NC}"; FAILED=$((FAILED + 1)); ERRORS+=("$*"); }',
		'info()     { echo -e "  ${CYAN}ℹ  $*${NC}"; }',
		'dim()      { echo -e "  ${DIM}$*${NC}"; }',
		"",
		"pad_name() {",
		'  local name="$1"',
		"  local pad=25",
		'  printf "%-${pad}s" "$name"',
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 1: Environment",
		"# ═══════════════════════════════════════════════════════════════════════",
		"phase_environment() {",
		'  if [ "$JSON_MODE" = false ]; then',
		'    echo ""',
		'    echo -e "${BOLD}── Phase 1: Environment ────────────────────────────────────${NC}"',
		'    echo ""',
		"  fi",
		"",
		"  # Docker",
		"  if command -v docker &>/dev/null; then",
		"    if docker info &>/dev/null 2>&1; then",
		'      pass "Docker daemon is running"',
		"      DOCKER_AVAILABLE=true",
		"    else",
		'      fail "Docker daemon is NOT running"',
		"      DOCKER_AVAILABLE=false",
		"    fi",
		"  else",
		'    warn_svc "Docker is not installed — running bare-metal checks only"',
		"    DOCKER_AVAILABLE=false",
		"  fi",
		"",
		"  # Docker Compose",
		'  if [ "$DOCKER_AVAILABLE" = true ]; then',
		"    if docker compose version &>/dev/null 2>&1; then",
		'      pass "Docker Compose v2 available"',
		"    else",
		'      warn_svc "Docker Compose v2 not found"',
		"    fi",
		"  fi",
		"",
		"  # .env",
		'  if [ -f ".env" ]; then',
		'    pass ".env file exists"',
		"    EMPTY_SECRETS=0",
		"    while IFS='=' read -r key value; do",
		'      [[ "$key" =~ ^#.*$ ]] && continue',
		'      [[ -z "$key" ]] && continue',
		'      if [[ "$key" =~ (PASSWORD|TOKEN|SECRET|SESSION_KEY|COOKIE|API_KEY) ]] && [[ -z "${value:-}" ]]; then',
		'        if [ "$VERBOSE" = true ]; then',
		'          warn_svc "Empty secret: $key"',
		"        fi",
		"        EMPTY_SECRETS=$((EMPTY_SECRETS + 1))",
		"      fi",
		"    done < .env 2>/dev/null || true",
		'    if [ "$EMPTY_SECRETS" -gt 0 ]; then',
		'      warn_svc "$EMPTY_SECRETS secret(s) are empty in .env"',
		"    else",
		'      pass "All secrets are populated"',
		"    fi",
		"  else",
		'    warn_svc ".env file not found"',
		"  fi",
		"",
		"  # Disk space",
		"  AVAIL_KB=$(df -k . 2>/dev/null | awk 'NR==2{print $4}' || echo \"0\")",
		"  AVAIL_GB=$((AVAIL_KB / 1024 / 1024))",
		'  if [ "$AVAIL_GB" -lt 2 ]; then',
		'    warn_svc "Low disk space: ${AVAIL_GB}GB available"',
		"  else",
		'    pass "Disk space: ${AVAIL_GB}GB available"',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 2: Container Status",
		"# ═══════════════════════════════════════════════════════════════════════",
		"check_container() {",
		'  local id="$1" name="$2" icon="$3"',
		"",
		"  local status restarts",
		'  status=$(docker compose ps "$id" --format json 2>/dev/null | head -1)',
		"",
		'  if [ -z "$status" ]; then',
		'    fail "$icon $(pad_name "$name") — Container not found"',
		"    return",
		"  fi",
		"",
		"  local state health_status",
		'  state=$(echo "$status" | grep -o \'"State":"[^"]*"\' | cut -d\'"\' -f4 || echo "unknown")',
		'  health_status=$(echo "$status" | grep -o \'"Health":"[^"]*"\' | cut -d\'"\' -f4 || echo "none")',
		"",
		'  restarts=$(docker inspect --format="{{.RestartCount}}" "$(docker compose ps -q "$id" 2>/dev/null | head -1)" 2>/dev/null || echo "0")',
		"",
		'  if [ "$state" = "running" ]; then',
		'    if [ "$health_status" = "healthy" ]; then',
		'      pass "$icon $(pad_name "$name") Running (healthy) restarts: $restarts"',
		'    elif [ "$health_status" = "starting" ]; then',
		'      warn_svc "$icon $(pad_name "$name") Running (starting) restarts: $restarts"',
		'    elif [ "$health_status" = "unhealthy" ]; then',
		'      fail "$icon $(pad_name "$name") Running (UNHEALTHY) restarts: $restarts"',
		"    else",
		'      pass "$icon $(pad_name "$name") Running restarts: $restarts"',
		"    fi",
		'    if [ "$restarts" -gt 5 ] 2>/dev/null; then',
		'      warn_svc "  └─ $name has restarted $restarts times (possible crash loop)"',
		"    fi",
		'  elif [ "$state" = "exited" ]; then',
		"    local exit_code",
		'    exit_code=$(docker inspect --format="{{.State.ExitCode}}" "$(docker compose ps -q "$id" 2>/dev/null | head -1)" 2>/dev/null || echo "?")',
		'    fail "$icon $(pad_name "$name") Exited (code $exit_code)"',
		'    if [ "$exit_code" = "137" ]; then',
		'      ERRORS+=("  └─ $name: OOM killed (exit 137). Increase memory limits.")',
		'    elif [ "$exit_code" = "1" ]; then',
		'      ERRORS+=("  └─ $name: Application error (exit 1). Check logs: docker compose logs $id")',
		"    fi",
		"  else",
		'    fail "$icon $(pad_name "$name") State: $state"',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 3: Port Reachability",
		"# ═══════════════════════════════════════════════════════════════════════",
		"check_port() {",
		'  local id="$1" port="$2" desc="$3"',
		"  if command -v nc &>/dev/null; then",
		'    if nc -z -w 2 localhost "$port" 2>/dev/null; then',
		'      dim "    Port $port ($desc) — reachable"',
		"    else",
		'      warn_svc "  └─ $id: Port $port ($desc) — NOT reachable"',
		"    fi",
		"  elif command -v curl &>/dev/null; then",
		'    if curl -sf --max-time 2 "http://localhost:$port/" &>/dev/null; then',
		'      dim "    Port $port ($desc) — reachable"',
		"    else",
		'      warn_svc "  └─ $id: Port $port ($desc) — NOT reachable"',
		"    fi",
		"  else",
		'    dim "    Port $port ($desc) — skipped (no nc or curl)"',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 4: Health Check Commands",
		"# ═══════════════════════════════════════════════════════════════════════",
		"check_health_cmd() {",
		'  local id="$1" cmd="$2"',
		'  local cid=$(docker compose ps -q "$id" 2>/dev/null | head -1)',
		'  [ -z "$cid" ] && return',
		'  if docker exec "$cid" sh -c "$cmd" &>/dev/null; then',
		'    dim "    Health command passed"',
		"  else",
		'    warn_svc "  └─ $id: Health check command failed"',
		'    if [ "$VERBOSE" = true ]; then dim "    Command: $cmd"; fi',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 5: Resource Usage",
		"# ═══════════════════════════════════════════════════════════════════════",
		"phase_resources() {",
		'  if [ "$JSON_MODE" = false ]; then',
		'    echo ""',
		'    echo -e "${BOLD}── Phase 5: Resource Usage ─────────────────────────────────${NC}"',
		'    echo ""',
		"  fi",
		'  docker stats --no-stream --format "table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\\t{{.MemPerc}}" 2>/dev/null || true',
		'  if [ "$VERBOSE" = false ] && [ "$JSON_MODE" = false ]; then',
		'    info "Use --verbose to see warnings for high memory usage"',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Phase 6: Log Scan",
		"# ═══════════════════════════════════════════════════════════════════════",
		"phase_logs() {",
		'  if [ "$QUICK_MODE" = true ]; then',
		'    if [ "$JSON_MODE" = false ]; then echo ""; info "Skipping log scan (--quick mode)"; fi',
		"    return",
		"  fi",
		'  if [ "$JSON_MODE" = false ]; then',
		'    echo ""',
		'    echo -e "${BOLD}── Phase 6: Log Scan ───────────────────────────────────────${NC}"',
		'    echo ""',
		"  fi",
		"  local has_errors=false",
		L("  for svc_id in ", svcIdList, "; do"),
		"    local error_lines",
		'    error_lines=$(docker compose logs --tail=50 "$svc_id" 2>/dev/null | grep -iE "(error|fatal|panic|exception|segfault|killed|oom)" | tail -5 || true)',
		'    if [ -n "$error_lines" ]; then',
		"      has_errors=true",
		'      warn_svc "$svc_id — found error patterns in logs:"',
		'      echo "$error_lines" | while IFS= read -r eline; do',
		'        dim "    | $eline"',
		"      done",
		"    fi",
		"  done",
		'  if [ "$has_errors" = false ] && [ "$JSON_MODE" = false ]; then',
		'    pass "No error patterns found in recent logs"',
		"  fi",
		"}",
		"",
		"# ── Bare-metal process check ────────────────────────────────────────",
		"check_process() {",
		'  local id="$1" name="$2" icon="$3"',
		"  if command -v systemctl &>/dev/null; then",
		'    if systemctl is-active --quiet "$id" 2>/dev/null; then',
		'      pass "$icon $(pad_name "$name") Active (systemd)"',
		"      return",
		"    fi",
		"  fi",
		'  if pgrep -f "$id" &>/dev/null; then',
		'    pass "$icon $(pad_name "$name") Running (process)"',
		"  else",
		'    fail "$icon $(pad_name "$name") NOT running"',
		"  fi",
		"}",
		"",
		"# ═══════════════════════════════════════════════════════════════════════",
		"# Main",
		"# ═══════════════════════════════════════════════════════════════════════",
		"",
		"DOCKER_AVAILABLE=false",
		"",
		'if [ "$JSON_MODE" = false ]; then',
		'  echo ""',
		'  echo "═══════════════════════════════════════════════════════════════════════"',
		L('  echo " 🐾 OpenClaw Stack Health Report — ', name, '"'),
		'  echo "═══════════════════════════════════════════════════════════════════════"',
		"fi",
		"",
		"phase_environment",
		"",
		'if [ "$DOCKER_AVAILABLE" = true ]; then',
		'  if [ "$JSON_MODE" = false ]; then',
		'    echo ""',
		'    echo -e "${BOLD}── Phase 2–4: Service Checks ──────────────────────────────${NC}"',
		'    echo ""',
		"  fi",
		"",
		...dockerChecks,
		"",
		"  phase_resources",
		"  phase_logs",
		"",
		"else",
		'  if [ "$JSON_MODE" = false ]; then',
		'    echo ""',
		'    echo -e "${BOLD}── Bare-Metal Service Checks ──────────────────────────────${NC}"',
		'    echo ""',
		"  fi",
		"",
		...bmChecks,
		"fi",
		"",
		"# ── Summary ──────────────────────────────────────────────────────────",
		'echo ""',
		'echo "═══════════════════════════════════════════════════════════════════════"',
		'echo ""',
		'echo -e "  ${BOLD}Summary${NC}: $TOTAL services checked"',
		'echo -e "  ${GREEN}Healthy: $HEALTHY${NC}  |  ${YELLOW}Warnings: $WARNING${NC}  |  ${RED}Failed: $FAILED${NC}"',
		"",
		"if [ ${#ERRORS[@]} -gt 0 ]; then",
		'  echo ""',
		'  echo -e "  ${BOLD}${RED}── Errors ─────────────────────────────────────────────────${NC}"',
		'  for e in "${ERRORS[@]}"; do',
		'    echo -e "  ${RED}$e${NC}"',
		"  done",
		"fi",
		"",
		'echo ""',
		'echo "═══════════════════════════════════════════════════════════════════════"',
		'echo ""',
		"",
		'if [ "$FAILED" -gt 0 ]; then',
		'  echo -e "  ${RED}Some services need attention. Run with --verbose for details.${NC}"',
		"  exit 1",
		"else",
		'  echo -e "  ${GREEN}🎉 All services are running!${NC}"',
		"  exit 0",
		"fi",
	];

	return `${lines.join("\n")}\n`;
}

// ─── PowerShell Script ──────────────────────────────────────────────────────

function generatePowerShellScript(resolved: ResolverOutput, options: HealthCheckOptions): string {
	const checks = extractServiceChecks(resolved);
	const name = options.projectName;
	const total = checks.length;

	// Build per-service docker check calls
	const dockerChecks: string[] = [];
	for (const svc of checks) {
		dockerChecks.push(L("    # ", svc.icon, " ", svc.name));
		dockerChecks.push(
			L(
				'    Test-Container -ServiceId "',
				svc.id,
				'" -ServiceName "',
				svc.name,
				'" -Icon "',
				svc.icon,
				'"',
			),
		);
		for (const p of svc.ports.filter((pp) => pp.exposed)) {
			dockerChecks.push(
				L(
					'    Test-Port -ServiceId "',
					svc.id,
					'" -Port ',
					String(p.host),
					' -Description "',
					p.description,
					'"',
				),
			);
		}
		dockerChecks.push("");
	}

	// Build per-service bare-metal check calls
	const bmChecks: string[] = [];
	for (const svc of checks) {
		bmChecks.push(L("    # ", svc.icon, " ", svc.name));
		bmChecks.push(
			L(
				'    Test-ProcessRunning -ServiceId "',
				svc.id,
				'" -ServiceName "',
				svc.name,
				'" -Icon "',
				svc.icon,
				'"',
			),
		);
		for (const p of svc.ports.filter((pp) => pp.exposed)) {
			bmChecks.push(
				L(
					'    Test-Port -ServiceId "',
					svc.id,
					'" -Port ',
					String(p.host),
					' -Description "',
					p.description,
					'"',
				),
			);
		}
		bmChecks.push("");
	}

	const svcIdList = checks.map((s) => `"${s.id}"`).join(", ");

	const lines: string[] = [
		"#Requires -Version 5.1",
		"<#",
		".SYNOPSIS",
		L("    OpenClaw Stack Health Check — ", name),
		"",
		".DESCRIPTION",
		"    Auto-generated verification script for your stack.",
		L(
			"    Checks ",
			String(total),
			" services: container status, port reachability, and log errors.",
		),
		"",
		".PARAMETER Quick",
		"    Skip log scanning for faster results.",
		"",
		".PARAMETER Json",
		"    Output results as JSON.",
		"",
		".EXAMPLE",
		"    .\\scripts\\health-check.ps1",
		"    .\\scripts\\health-check.ps1 -Quick",
		"    .\\scripts\\health-check.ps1 -Json",
		"#>",
		"param(",
		"    [switch]$Quick,",
		"    [switch]$Json,",
		"    [switch]$Detailed",
		")",
		"",
		'$ErrorActionPreference = "Continue"',
		"",
		"# ── Counters ─────────────────────────────────────────────────────────",
		L("$script:Total = ", String(total)),
		"$script:Healthy = 0",
		"$script:Warnings = 0",
		"$script:Failed = 0",
		"$script:Errors = @()",
		"$script:ServiceResults = @()",
		"$script:DockerAvailable = $false",
		"",
		"# ── Helpers ──────────────────────────────────────────────────────────",
		"",
		'function Write-Pass($msg)    { Write-Host "  ✅ $msg" -ForegroundColor Green; $script:Healthy++ }',
		'function Write-Warn($msg)    { Write-Host "  ⚠️  $msg" -ForegroundColor Yellow; $script:Warnings++ }',
		'function Write-Fail($msg)    { Write-Host "  ❌ $msg" -ForegroundColor Red; $script:Failed++; $script:Errors += $msg }',
		'function Write-Info($msg)    { Write-Host "  ℹ  $msg" -ForegroundColor Cyan }',
		'function Write-Dim($msg)     { Write-Host "  $msg" -ForegroundColor DarkGray }',
		"",
		"function Pad-Name([string]$n) { return $n.PadRight(25) }",
		"",
		"# ═════════════════════════════════════════════════════════════════════",
		"# Phase 1: Environment",
		"# ═════════════════════════════════════════════════════════════════════",
		"function Test-Environment {",
		"    if (-not $Json) {",
		'        Write-Host ""',
		'        Write-Host "── Phase 1: Environment ────────────────────────────────────" -ForegroundColor White',
		'        Write-Host ""',
		"    }",
		"    try {",
		"        $null = docker info 2>&1",
		"        if ($LASTEXITCODE -eq 0) {",
		'            Write-Pass "Docker daemon is running"',
		"            $script:DockerAvailable = $true",
		"        } else {",
		'            Write-Fail "Docker daemon is NOT running"',
		"        }",
		"    } catch {",
		'        Write-Warn "Docker is not installed — running bare-metal checks only"',
		"    }",
		"    if ($script:DockerAvailable) {",
		"        try {",
		"            $null = docker compose version 2>&1",
		"            if ($LASTEXITCODE -eq 0) {",
		'                Write-Pass "Docker Compose v2 available"',
		"            } else {",
		'                Write-Warn "Docker Compose v2 not found"',
		"            }",
		"        } catch {",
		'            Write-Warn "Docker Compose not available"',
		"        }",
		"    }",
		'    $envPath = Join-Path $PSScriptRoot "..\\.env"',
		"    if (Test-Path $envPath) {",
		'        Write-Pass ".env file exists"',
		"        $emptySecrets = 0",
		"        Get-Content $envPath | ForEach-Object {",
		'            if ($_ -match "(PASSWORD|TOKEN|SECRET|SESSION_KEY|COOKIE|API_KEY).*=\\s*$") { $emptySecrets++ }',
		"        }",
		"        if ($emptySecrets -gt 0) {",
		'            Write-Warn "$emptySecrets secret(s) are empty in .env"',
		"        } else {",
		'            Write-Pass "All secrets are populated"',
		"        }",
		"    } else {",
		'        Write-Warn ".env file not found"',
		"    }",
		"    $drive = (Get-Item $PSScriptRoot).PSDrive",
		"    $freeGB = [math]::Round($drive.Free / 1GB, 1)",
		"    if ($freeGB -lt 2) {",
		'        Write-Warn "Low disk space: ${freeGB}GB available"',
		"    } else {",
		'        Write-Pass "Disk space: ${freeGB}GB available"',
		"    }",
		"}",
		"",
		"# ═════════════════════════════════════════════════════════════════════",
		"# Phase 2: Container Check",
		"# ═════════════════════════════════════════════════════════════════════",
		"function Test-Container {",
		"    param([string]$ServiceId, [string]$ServiceName, [string]$Icon)",
		"    try {",
		"        $status = docker compose ps $ServiceId --format json 2>&1 | ConvertFrom-Json",
		"    } catch {",
		'        Write-Fail "$Icon $(Pad-Name $ServiceName) Container not found"',
		"        return",
		"    }",
		"    if (-not $status) {",
		'        Write-Fail "$Icon $(Pad-Name $ServiceName) Container not found"',
		"        return",
		"    }",
		"    $state = $status.State",
		"    $health = $status.Health",
		'    if ($state -eq "running") {',
		'        if ($health -eq "healthy") {',
		'            Write-Pass "$Icon $(Pad-Name $ServiceName) Running (healthy)"',
		'        } elseif ($health -eq "starting") {',
		'            Write-Warn "$Icon $(Pad-Name $ServiceName) Running (starting)"',
		'        } elseif ($health -eq "unhealthy") {',
		'            Write-Fail "$Icon $(Pad-Name $ServiceName) Running (UNHEALTHY)"',
		"        } else {",
		'            Write-Pass "$Icon $(Pad-Name $ServiceName) Running"',
		"        }",
		'    } elseif ($state -eq "exited") {',
		'        Write-Fail "$Icon $(Pad-Name $ServiceName) Exited"',
		"    } else {",
		'        Write-Fail "$Icon $(Pad-Name $ServiceName) State: $state"',
		"    }",
		"}",
		"",
		"# ═════════════════════════════════════════════════════════════════════",
		"# Phase 3: Port Check",
		"# ═════════════════════════════════════════════════════════════════════",
		"function Test-Port {",
		"    param([string]$ServiceId, [int]$Port, [string]$Description)",
		"    try {",
		"        $tcp = New-Object System.Net.Sockets.TcpClient",
		'        $tcp.ConnectAsync("localhost", $Port).Wait(2000) | Out-Null',
		"        if ($tcp.Connected) {",
		'            Write-Dim "    Port $Port ($Description) — reachable"',
		"            $tcp.Close()",
		"        } else {",
		'            Write-Warn "  └─ ${ServiceId}: Port $Port ($Description) — NOT reachable"',
		"        }",
		"    } catch {",
		'        Write-Warn "  └─ ${ServiceId}: Port $Port ($Description) — NOT reachable"',
		"    }",
		"}",
		"",
		"# ── Bare-metal process check ────────────────────────────────────────",
		"function Test-ProcessRunning {",
		"    param([string]$ServiceId, [string]$ServiceName, [string]$Icon)",
		"    $svc = Get-Service -Name $ServiceId -ErrorAction SilentlyContinue",
		"    if ($svc) {",
		'        if ($svc.Status -eq "Running") {',
		'            Write-Pass "$Icon $(Pad-Name $ServiceName) Active (service)"',
		"        } else {",
		'            Write-Fail "$Icon $(Pad-Name $ServiceName) $($svc.Status)"',
		"        }",
		"        return",
		"    }",
		"    $proc = Get-Process -Name $ServiceId -ErrorAction SilentlyContinue",
		"    if ($proc) {",
		'        Write-Pass "$Icon $(Pad-Name $ServiceName) Running (process)"',
		"    } else {",
		'        Write-Fail "$Icon $(Pad-Name $ServiceName) NOT running"',
		"    }",
		"}",
		"",
		"# ═════════════════════════════════════════════════════════════════════",
		"# Phase 6: Log Scan",
		"# ═════════════════════════════════════════════════════════════════════",
		"function Test-Logs {",
		"    if ($Quick) {",
		'        if (-not $Json) { Write-Info "Skipping log scan (-Quick mode)" }',
		"        return",
		"    }",
		"    if (-not $Json) {",
		'        Write-Host ""',
		'        Write-Host "── Phase 6: Log Scan ───────────────────────────────────────" -ForegroundColor White',
		'        Write-Host ""',
		"    }",
		"    $hasErrors = $false",
		L("    $svcIds = @(", svcIdList, ")"),
		"    foreach ($svcId in $svcIds) {",
		"        try {",
		"            $logs = docker compose logs --tail=50 $svcId 2>&1 | Out-String",
		'            $errorLines = $logs -split "`n" | Where-Object { $_ -match "(error|fatal|panic|exception|segfault|killed|oom)" } | Select-Object -Last 5',
		"            if ($errorLines) {",
		"                $hasErrors = $true",
		'                Write-Warn "$svcId — found error patterns in logs:"',
		'                $errorLines | ForEach-Object { Write-Dim "    | $_" }',
		"            }",
		"        } catch {}",
		"    }",
		"    if (-not $hasErrors -and -not $Json) {",
		'        Write-Pass "No error patterns found in recent logs"',
		"    }",
		"}",
		"",
		"# ═════════════════════════════════════════════════════════════════════",
		"# Main",
		"# ═════════════════════════════════════════════════════════════════════",
		"",
		"if (-not $Json) {",
		'    Write-Host ""',
		'    Write-Host "═══════════════════════════════════════════════════════════════════════" ',
		L('    Write-Host " 🐾 OpenClaw Stack Health Report — ', name, '"'),
		'    Write-Host "═══════════════════════════════════════════════════════════════════════"',
		"}",
		"",
		"Test-Environment",
		"",
		"if ($script:DockerAvailable) {",
		"    if (-not $Json) {",
		'        Write-Host ""',
		'        Write-Host "── Phase 2–4: Service Checks ──────────────────────────────" -ForegroundColor White',
		'        Write-Host ""',
		"    }",
		"",
		...dockerChecks,
		"    Test-Logs",
		"} else {",
		"    if (-not $Json) {",
		'        Write-Host ""',
		'        Write-Host "── Bare-Metal Service Checks ──────────────────────────────" -ForegroundColor White',
		'        Write-Host ""',
		"    }",
		"",
		...bmChecks,
		"}",
		"",
		"# ── Summary ──────────────────────────────────────────────────────────",
		"if ($Json) {",
		"    $result = @{",
		L('        project = "', name, '"'),
		'        timestamp = (Get-Date -Format "o")',
		"        summary = @{",
		"            total = $script:Total",
		"            healthy = $script:Healthy",
		"            warnings = $script:Warnings",
		"            failed = $script:Failed",
		"        }",
		"        errors = $script:Errors",
		"    }",
		"    $result | ConvertTo-Json -Depth 5",
		"} else {",
		'    Write-Host ""',
		'    Write-Host "═══════════════════════════════════════════════════════════════════════"',
		'    Write-Host ""',
		'    Write-Host "  Summary: $($script:Total) services checked"',
		'    Write-Host "  Healthy: $($script:Healthy)" -ForegroundColor Green -NoNewline',
		'    Write-Host "  |  Warnings: $($script:Warnings)" -ForegroundColor Yellow -NoNewline',
		'    Write-Host "  |  Failed: $($script:Failed)" -ForegroundColor Red',
		"    if ($script:Errors.Count -gt 0) {",
		'        Write-Host ""',
		'        Write-Host "  ── Errors ──────────────────────────────────────────────────" -ForegroundColor Red',
		'        $script:Errors | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }',
		"    }",
		'    Write-Host ""',
		'    Write-Host "═══════════════════════════════════════════════════════════════════════"',
		'    Write-Host ""',
		"    if ($script:Failed -gt 0) {",
		'        Write-Host "  Some services need attention. Run with -Detailed for more." -ForegroundColor Red',
		"        exit 1",
		"    } else {",
		'        Write-Host "  🎉 All services are running!" -ForegroundColor Green',
		"        exit 0",
		"    }",
		"}",
	];

	return `${lines.join("\n")}\n`;
}
